language: shell
os: linux
arch: amd64
dist: bionic

services: docker

branches:
  only:
    - master

before_install:
  - docker-compose --version
  - docker --version

script:
  - docker-compose up --build --exit-code-from vue-component-button

notifications:
  email:
    recipients:
      - alvisisme@163.com
    on_success: never
    on_failure: always